development:
  aws_access_key_id: 0J5HEXT0313CQHNJRYR2
  aws_secret_access_key: afI36k8icPw2iuVyDz80AE8MapnXM0erLl9MUNBo
  aws_bucket: voicememo-uploads

test:
  aws_access_key_id: 0J5HEXT0313CQHNJRYR2
  aws_secret_access_key: afI36k8icPw2iuVyDz80AE8MapnXM0erLl9MUNBo
  aws_bucket: voicememo-uploads

production:
  aws_access_key_id: 0J5HEXT0313CQHNJRYR2
  aws_secret_access_key: afI36k8icPw2iuVyDz80AE8MapnXM0erLl9MUNBo
  aws_bucket: voicememo-uploads
